clc;
clear all;

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\PS!\CO2_Anomaly_detection\CODE\Anomaly_detect\dataset\class1\p\Simulink_Data.xlsx
%    Worksheet: Sheet2
%
% Auto-generated by MATLAB on 17-Jul-2019 17:28:00

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = "Sheet2";
opts.DataRange = "A2:I14402";

% Specify column names and types
opts.VariableNames = ["Time", "CO2_Zone_1", "CO2_Zone_2", "CO2_Zone_3", "CO2_Zone_4", "CO2_Zone_5", "CO2_Zone_6", "flightNo", "tailNo"];
opts.SelectedVariableNames = ["Time", "CO2_Zone_1", "CO2_Zone_2", "CO2_Zone_3", "CO2_Zone_4", "CO2_Zone_5", "CO2_Zone_6", "flightNo", "tailNo"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "categorical", "categorical"];
opts = setvaropts(opts, [8, 9], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("D:\PS!\CO2_Anomaly_detection\CODE\Anomaly_detect\dataset\class1\p\Simulink_Data.xlsx", opts, "UseExcel", false);

%% Convert to output type
Time = tbl.Time;
CO2_Zone_1 = tbl.CO2_Zone_1;
CO2_Zone_2 = tbl.CO2_Zone_2;
CO2_Zone_3 = tbl.CO2_Zone_3;
CO2_Zone_4 = tbl.CO2_Zone_4;
CO2_Zone_5 = tbl.CO2_Zone_5;
CO2_Zone_6 = tbl.CO2_Zone_6;
flightNo = tbl.flightNo;
tailNo = tbl.tailNo;

%% Clear temporary variables
clear opts tbl

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\PS!\CO2_Anomaly_detection\CODE\Anomaly_detect\dataset\class1\p\Simulink_Data2.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 17-Jul-2019 17:28:37

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 13);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:M241";

% Specify column names and types
opts.VariableNames = ["Time2", "CO2min_Zone_1", "CO2min_Zone_2", "CO2min_Zone_3", "CO2min_Zone_4", "CO2min_Zone_5", "CO2min_Zone_6", "flightNo2", "t_sim", "p_sim", "h_sim", "tailNo2", "pas_cnt"];
opts.SelectedVariableNames = ["Time2", "CO2min_Zone_1", "CO2min_Zone_2", "CO2min_Zone_3", "CO2min_Zone_4", "CO2min_Zone_5", "CO2min_Zone_6", "flightNo2", "t_sim", "p_sim", "h_sim", "tailNo2", "pas_cnt"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "categorical", "double", "double", "double", "categorical", "double"];
opts = setvaropts(opts, [8, 12], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("D:\PS!\CO2_Anomaly_detection\CODE\Anomaly_detect\dataset\class1\p\Simulink_Data2.xlsx", opts, "UseExcel", false);

%% Convert to output type
Time2 = tbl.Time2;
CO2min_Zone_1 = tbl.CO2min_Zone_1;
CO2min_Zone_2 = tbl.CO2min_Zone_2;
CO2min_Zone_3 = tbl.CO2min_Zone_3;
CO2min_Zone_4 = tbl.CO2min_Zone_4;
CO2min_Zone_5 = tbl.CO2min_Zone_5;
CO2min_Zone_6 = tbl.CO2min_Zone_6;
flightNo2 = tbl.flightNo2;
t_sim = tbl.t_sim;
p_sim = tbl.p_sim;
h_sim = tbl.h_sim;
tailNo2 = tbl.tailNo2;
pas_cnt = tbl.pas_cnt;

%% Clear temporary variables
clear opts tbl



CO2_Zone_1(1)=[];
CO2_Zone_2(1)=[];
CO2_Zone_3(1)=[];
CO2_Zone_4(1)=[];
CO2_Zone_5(1)=[];
CO2_Zone_6(1)=[];
tailNo(1)=[];
flightNo(1)=[];

k=0;
for i = 1:240
    for j = 1:60
        k=k+1;
        temp(k)=t_sim(i);
        press(k)=p_sim(i);
        humid(k)=h_sim(i);
        pass(k)=pas_cnt(i);
        
    end
end
humid_f= humid.';
temp_f=temp.';
press_f=press.';
pass_f=pass.';

final_array=cat(2,CO2_Zone_1,CO2_Zone_2,CO2_Zone_3,CO2_Zone_4,CO2_Zone_5,CO2_Zone_6,temp_f,press_f,humid_f,pass_f);

final_table=array2table(final_array,'VariableNames',{'CO2_Zone_1','CO2_Zone_2','CO2_Zone_3','CO2_Zone_4','CO2_Zone_5','CO2_Zone_6','temp_f','press_f','humid_f','pass_f'});

file_name=strcat('dataset_4hr_pascnt_',num2str(pass_f(4)),'.xlsx');
writetable(final_table,file_name);