clc 
clear all
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\PS!\CO2_Anomaly_detection\CODE\Anomaly_detect\final training data\C3_P186_labeled.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 18-Nov-2019 09:55:34

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 22);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:V10801";

% Specify column names and types
opts.VariableNames = ["VarName1", "CO2_Zone_1", "dz1", "CO2_Zone_2", "dz2", "CO2_Zone_3", "dz3", "CO2_Zone_4", "dz4", "CO2_Zone_5", "dz5", "CO2_Zone_6", "dz6", "temp_f", "press_f", "humid_f", "pass_f", "class_0", "class_1", "class_2", "class_3", "class_4"];
opts.SelectedVariableNames = ["VarName1", "CO2_Zone_1", "dz1", "CO2_Zone_2", "dz2", "CO2_Zone_3", "dz3", "CO2_Zone_4", "dz4", "CO2_Zone_5", "dz5", "CO2_Zone_6", "dz6", "temp_f", "press_f", "humid_f", "pass_f", "class_0", "class_1", "class_2", "class_3", "class_4"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
tbl = readtable("D:\PS!\CO2_Anomaly_detection\CODE\Anomaly_detect\final training data\C1_P10_labeled.xlsx", opts, "UseExcel", false);

%% Convert to output type
VarName1 = tbl.VarName1;
CO2_Zone_1 = tbl.CO2_Zone_1;
dz1 = tbl.dz1;
CO2_Zone_2 = tbl.CO2_Zone_2;
dz2 = tbl.dz2;
CO2_Zone_3 = tbl.CO2_Zone_3;
dz3 = tbl.dz3;
CO2_Zone_4 = tbl.CO2_Zone_4;
dz4 = tbl.dz4;
CO2_Zone_5 = tbl.CO2_Zone_5;
dz5 = tbl.dz5;
CO2_Zone_6 = tbl.CO2_Zone_6;
dz6 = tbl.dz6;
temp_f = tbl.temp_f;
press_f = tbl.press_f;
humid_f = tbl.humid_f;
pass_f = tbl.pass_f;
class_0 = tbl.class_0;
class_1 = tbl.class_1;
class_2 = tbl.class_2;
class_3 = tbl.class_3;
class_4 = tbl.class_4;

%% Clear temporary variables
clear opts tbl




%%
subplot(8,1,1)
plot(CO2_Zone_1)
subplot(8,1,2)
plot(dz1)

subplot(8,1,3)
plot(CO2_Zone_2)
subplot(8,1,4)
plot(dz2)

subplot(8,1,5)
plot(CO2_Zone_3)
subplot(8,1,6)
plot(dz3)
subplot(8,1,7)
plot(class_1)
subplot(8,1,8)
plot(class_4)









